### ISSUE TITLE
How to handle left recursive parsing?

### ISSUE THREAD

**Issue by asmwarrior** [axilmar/parserlib#9]
Hi, I see this:

> For recursive grammars, parse expressions must be wrapped into a `Rule<>` instance.

What does this mean?

Can you give a good or wrong example code?

For my understanding, PEG like grammar is just like calling a lot of functions. I know this as I'm one of the developers in this project: [joemalle/limn: A tiny parser designed to compile quickly](https://github.com/joemalle/limn)

Thanks.

**Comment by axilmar** [comment]
A grammar is recursive when a rule is part of a production, and the production is part of the rule. For example:

a = b a c
    | d
    
In the above, the production 'b a c' contains rule 'a', and then rule 'a' is assigned the production 'b a c'.
    
In order to achieve this in C++, an object can be wrapped into a reference before being constructed. Example:

Rule<> r = b >> r >> a
               | d;
              
In the above, Rule<> r is used before being constructed, so it is kept by reference into the parse tree.

In this library, any parsing expression can be kept into a Rule<> instance. Rule<> internally keeps a copy of the expression allocated on the heap, wrapped into a ParserWrapper class and accessed by interface ParserInterface. I.e. the class Rule<> erases the type of the supplied expression from compile time.
